version: '2'
services:
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app/client
    ports:
      - '3000:3000'
    depends_on:
      - api
    # following lines added to prevent client exiting with code 0 on build
    stdin_open: true
    tty: true
  api:
    build: ./api
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
